BEGIN;


CREATE TABLE IF NOT EXISTS public.aerolineas
(
    id_aerolinea bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    celular character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    imagen bigint NOT NULL,
    CONSTRAINT aerolineas_pkey PRIMARY KEY (id_aerolinea),
    CONSTRAINT uk3v623r7rb1e9ml66wb41awf98 UNIQUE (imagen)
);

CREATE TABLE IF NOT EXISTS public.asientos
(
    id_asiento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(10, 2),
    id_avion bigint,
    usuario_reservado bigint,
    CONSTRAINT asientos_pkey PRIMARY KEY (id_asiento)
);

CREATE TABLE IF NOT EXISTS public.aviones
(
    id_avion bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    capacidad integer NOT NULL,
    modelo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT aviones_pkey PRIMARY KEY (id_avion)
);

CREATE TABLE IF NOT EXISTS public.ciudades
(
    id_ciudad bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default",
    region bigint,
    CONSTRAINT ciudades_pkey PRIMARY KEY (id_ciudad)
);

CREATE TABLE IF NOT EXISTS public.imagenes
(
    id_imagen bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    key_s3 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre_original character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT imagenes_pkey PRIMARY KEY (id_imagen),
    CONSTRAINT ukcowcr29tijr76j3t4rm9sbtu3 UNIQUE (key_s3)
);

CREATE TABLE IF NOT EXISTS public.pagos
(
    id_pago bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_pago timestamp(6) without time zone NOT NULL,
    metodo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombres_pagador character varying(100) COLLATE pg_catalog."default" NOT NULL,
    numero_documento character varying(255) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_documento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    total numeric(10, 2),
    usuario bigint,
    CONSTRAINT pagos_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.paises
(
    id_pais bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT paises_pkey PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.pasajeros
(
    id_pasajero bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    celular character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    genero character varying(255) COLLATE pg_catalog."default",
    infante boolean NOT NULL,
    nombres character varying(255) COLLATE pg_catalog."default",
    numero_documento character varying(255) COLLATE pg_catalog."default" NOT NULL,
    primer_apellido character varying(255) COLLATE pg_catalog."default",
    segundo_apellido character varying(255) COLLATE pg_catalog."default",
    id_asiento bigint,
    reserva_id bigint,
    CONSTRAINT pasajeros_pkey PRIMARY KEY (id_pasajero),
    CONSTRAINT uk7bmj5dcv58hb5ff2575xypyi7 UNIQUE (id_asiento),
    CONSTRAINT ukj2jwhf525ah53chnwdlw333yq UNIQUE (numero_documento)
);

CREATE TABLE IF NOT EXISTS public.regiones
(
    id_region bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    pais bigint,
    CONSTRAINT regiones_pkey PRIMARY KEY (id_region)
);

CREATE TABLE IF NOT EXISTS public.reservas
(
    id_reserva bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado character varying(255) COLLATE pg_catalog."default",
    numero_reserva character varying(255) COLLATE pg_catalog."default" NOT NULL,
    pago_id bigint,
    vuelo_id bigint,
    usuario bigint,
    CONSTRAINT reservas_pkey PRIMARY KEY (id_reserva),
    CONSTRAINT uk6hakffa4nlx9ct893cpph3rqh UNIQUE (numero_reserva),
    CONSTRAINT uko3y3na19fnbxytl8kbwekkjmu UNIQUE (pago_id)
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    id_ticket bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    qr_code text COLLATE pg_catalog."default" NOT NULL,
    id_reserva bigint NOT NULL,
    id_usuario bigint NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id_ticket)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    celular character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estado boolean NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    primer_apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    segundo_apellido character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vuelos
(
    id_vuelo bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    hora_llegada timestamp(6) without time zone NOT NULL,
    hora_salida timestamp(6) without time zone NOT NULL,
    lugar_llegada character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lugar_salida character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_aerolinea bigint NOT NULL,
    id_avion bigint NOT NULL,
    id_ciudad_llegada bigint NOT NULL,
    id_ciudad_salida bigint NOT NULL,
    CONSTRAINT vuelos_pkey PRIMARY KEY (id_vuelo)
);

ALTER TABLE IF EXISTS public.aerolineas
    ADD CONSTRAINT fk1bbb3qo8433c7dkiwlu8rop68 FOREIGN KEY (imagen)
    REFERENCES public.imagenes (id_imagen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk3v623r7rb1e9ml66wb41awf98
    ON public.aerolineas(imagen);


ALTER TABLE IF EXISTS public.asientos
    ADD CONSTRAINT fktdqqlp9mg6re3umrkcj7m60ie FOREIGN KEY (id_avion)
    REFERENCES public.aviones (id_avion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ciudades
    ADD CONSTRAINT fkesfwf3ufciqo04dt9e55jwlf6 FOREIGN KEY (region)
    REFERENCES public.regiones (id_region) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pasajeros
    ADD CONSTRAINT fk4je2gmhaf9wblneo5vh8pwg4t FOREIGN KEY (id_asiento)
    REFERENCES public.asientos (id_asiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk7bmj5dcv58hb5ff2575xypyi7
    ON public.pasajeros(id_asiento);


ALTER TABLE IF EXISTS public.pasajeros
    ADD CONSTRAINT fkglyb53vlxo931bfyxrrmx90hf FOREIGN KEY (reserva_id)
    REFERENCES public.reservas (id_reserva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.regiones
    ADD CONSTRAINT fk8l2lk85ojcpyigj79veygm48g FOREIGN KEY (pais)
    REFERENCES public.paises (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reservas
    ADD CONSTRAINT fkdnuhxoikoodjg9o6yaiubx972 FOREIGN KEY (usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reservas
    ADD CONSTRAINT fkgoaxtt66619kpmyf8ne1ed8jh FOREIGN KEY (pago_id)
    REFERENCES public.pagos (id_pago) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uko3y3na19fnbxytl8kbwekkjmu
    ON public.reservas(pago_id);


ALTER TABLE IF EXISTS public.reservas
    ADD CONSTRAINT fkqcqeer7p8pw6wkaq7ekyssjgm FOREIGN KEY (vuelo_id)
    REFERENCES public.vuelos (id_vuelo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT fka4jda6vdeg3d29ujop9c4mfbi FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT fkbv9l8rq0iaib3p4vhhi4pir98 FOREIGN KEY (id_reserva)
    REFERENCES public.reservas (id_reserva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vuelos
    ADD CONSTRAINT fk1dnqfbcn9o3p141yx3c0fj0x3 FOREIGN KEY (id_ciudad_salida)
    REFERENCES public.ciudades (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vuelos
    ADD CONSTRAINT fkfxhcdt107eb3bo3xvqsk3ax2d FOREIGN KEY (id_aerolinea)
    REFERENCES public.aerolineas (id_aerolinea) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vuelos
    ADD CONSTRAINT fkkknvbov53vpbsxjmxfjkyeq79 FOREIGN KEY (id_avion)
    REFERENCES public.aviones (id_avion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vuelos
    ADD CONSTRAINT fkqkxsppestdnnas9w2nbbfchkw FOREIGN KEY (id_ciudad_llegada)
    REFERENCES public.ciudades (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;