spring.application.name=demo
server.port=8080

# Configuración de BD
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_airline
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra los parámetros de las consultas SQL (valores reales)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cambiar la ruta donde se carga Swagger UI
springdoc.swagger-ui.path=/documentacion-api

# JWT
security.jwt.secret-key=155a103d7bf5de27895ded35d5576d0df849a754deca0f0890d681343a80a970

# CLOUDFLARE R2
cloudflare.r2.accessKey=7c6e8e3c022664b999da1419345eddce
cloudflare.r2.secretKey=a303669d366f7456531e40bd50f2dccec64126509a628d67c17b667ab01c0833
cloudflare.r2.bucket=imgproductos
cloudflare.r2.endpoint=https://8a76c0b67cb4505b702d73fe6ea0db2d.r2.cloudflarestorage.com
cloudflare.r2.region=us-east-1
