spring.application.name=demo
server.port=8080

# Configuración de BD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra los parámetros de las consultas SQL (valores reales)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cambiar la ruta donde se carga Swagger UI
springdoc.swagger-ui.path=/documentacion-api

# JWT
security.jwt.secret-key=${JWT_SECRET}

# CLOUDFLARE R2
cloudflare.r2.accessKey=${R2_ACCESS_KEY}
cloudflare.r2.secretKey=${R2_SECRET_KEY}
cloudflare.r2.bucket=${R2_BUCKET}
cloudflare.r2.endpoint=${R2_ENDPOINT}
cloudflare.r2.region=${R2_REGION}
